package com.example.authstarter.module.auth.service.notification;

import com.example.authstarter.module.auth.exceptions.AuthenticationException;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class EmailService {

    private final JavaMailSender mailSender;

    @Value("${app.frontend.url}")
    private String frontendUrl;

    @Async("emailExecutor")
    public void sendVerificationEmail(String email, String token) {
        String link = frontendUrl + "/verify-email?token=" + token;
        sendHtmlEmail(email, "Verify your email",
                "Click <a href=\"" + link + "\">here</a> to verify your account.");
    }

    @Async("emailExecutor")
    public void sendPasswordResetEmail(String email, String token) {
        String link = frontendUrl + "/reset-password?token=" + token;
        sendHtmlEmail(email, "Reset your password",
                "Click <a href=\"" + link +
                        "\">here</a> to reset your password. Link expires in 15 minutes.");
    }

    /**
     * Sends a reminder to users who attempt a password reset but only have
     * social login methods linked to their account.
     */
    @Async("emailExecutor")
    public void sendSocialLoginReminder(String email, String provider) {
        String formattedProvider = provider.substring(0, 1).toUpperCase() +
                provider.substring(1).toLowerCase();

        String subject = "Information regarding your password reset request";

        // 2. Build the message body
        // In a real prod app, you'd use a Thymeleaf or FreeMarker template here.
        String message = String.format(
                """
                        Hello,
                       \s
                        We received a request to reset the password for the account associated with this email address.
                       \s
                        However, our records show that you typically log in using your **%s** account. \
                        Because of this, you do not have a separate password set up on our platform.
                       \s
                        **How to log in:**
                        Simply go to the login page and click the 'Continue with %s' button.
                       \s
                        If you would like to create a unique password for this account, please log in via %s first, \
                        then visit your Account Settings to set a new password.
                       \s
                        If you did not request this, you can safely ignore this email.
                       \s
               \s""",
                formattedProvider, formattedProvider, formattedProvider
        );

        // 3. Send the email (using your existing mail infrastructure)
        sendHtmlEmail(email, subject, message);
    }

    /**
     * Sends a high-security verification code to the user's email
     * to authorize the soft-deletion of their account.
     *
     * @param email The user's registered email address.
     * @param code  The 6-digit numeric OTP generated by the OtpService.
     */
    @Async("emailExecutor")
    public void sendAccountDeletionCode(String email, String code) {
        String subject = "URGENT: Account Deletion Security Code";

        // Build the message body
        String message = String.format(
                """
                        Hello,
                        
                        We received a request to permanently delete your account. \
                        To confirm this action, please enter the following verification code in the app:
                        
                        --- %s ---
                        
                        This code will expire in 10 minutes.
                        
                        **WARNING:** Deleting your account will disable your access and begin the data removal process. \
                        If you did not request this, please change your password immediately and ignore this email.""",
                code
        );

        // Dispatch via your mail provider
        sendHtmlEmail(email, subject, message);
    }

    /**
     * Sends a confirmation email to the user's proposed new email address.
     * Includes a secure token link to finalize the change.
     *
     * @param newEmail The target email address.
     * @param token    The unique verification token generated for this request.
     */
    @Async("emailExecutor")
    public void sendEmailChangeConfirmation(String newEmail, String token) {
        // 1. Construct the confirmation URL pointing to your React Frontend
        // Example: https://myapp.com/confirm-email-change?token=xyz
        String confirmationUrl = frontendUrl + "/auth/confirm-email-change?token=" + token;

        String subject = "Confirm your new email address";

        // 2. Build the message body
        // PROD TIP: Use a template engine like Thymeleaf for HTML emails in the future
        String message = String.format(
                """
                        Hello,
                        
                        You requested to change your account email to %s.
                        
                        To complete this process, please click the link below to verify this address:
                        %s
                        
                        This link will expire in 2 hours.
                        
                        If you did not request this change, please ignore this email. Your current email remains secure.""",
                newEmail, confirmationUrl
        );

        // 3. Dispatch via your mail provider
        sendHtmlEmail(newEmail, subject, message);
    }

    private void sendHtmlEmail(String to, String subject, String body) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setText(body, true);
            mailSender.send(message);
        } catch (MessagingException e) {
            throw new AuthenticationException("Failed to send email");
        }
    }
}
